
list = 
          ['andaman and nicobar islands',17],
          ['arunanchal pradesh',1],
          ['andhra pradesh',813],
          ['assam',35],
          ['bihar',126],
          ['chandigarh',27],
          ['chhattisgarh',36],
          ['nct of delhi',2156],
          ['goa',7],
          ['gujarat',2272], 
          ['haryana',254],
          ['himachal pradesh',39],
          ['jammu and kashmir',380], 
          ['jharkhand',45],
          ['karnataka',425],
          ['kerala',427],
          ['ladakh',18],
          ['madhya pradesh',1592],
          ['maharashtra',5221],
          ['manipur',2],
          ['meghalaya',12],
          ['mizoram',1],
          ['nagaland',1],
          ['odisha',82],
          ['puducherry',7],
          ['punjab',251],
          ['rajasthan',1801],
          ['tamil nadu',1596],
          ['telangana',945],
          ['tripura',2],
          ['uttarakhand',46],
          ['uttar pradesh',1412],
          ['west bengal',12]
        
print(list[10])        